language: php
sudo: false

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

matrix:
  allow_failures:
  - php: hhvm

services:
  - mysql

install:
  - composer install -o --no-interaction

before_script:
  - mysql -e 'create database symphony_test;'

script:
  - symphony/conductor install test/travis_ci_config.php --override --no-interaction -vvv
  - ./vendor/bin/phpcs --colors --extensions=php symphony/ install/


cache:
  directories:
    - $HOME/.composer/cache
